<a href="https://colab.research.google.com/github/Honaht01/PDA_sol/blob/main/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Выполнил: Григорьев П.К.
# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [86]:
import numpy as np
print(np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [87]:
ZVec=np.zeros(10)
print(ZVec)
print("Количество элементов: {}".format(ZVec.size))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Количество элементов: 10


3) Создать вектор заполненный 7-ами размера 7

In [89]:
SVec=np.full(7,7)
print(SVec)
print("Количество элементов: {}".format(SVec.size))

[7 7 7 7 7 7 7]
Количество элементов: 7


4) Создать вектор заполненный четными числами от 10 до 100

In [90]:
EVec = np.arange(10, 101, 2)
print(EVec)
print("Количество элементов: {}".format(EVec.size))

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]
Количество элементов: 46


5) Создать массив случайных чисел и развернуть его задом наперёд

In [91]:
RVec = np.random.random(5)
RRVec = RVec[: : -1]
print(RVec)
print("Количество элементов: {}".format(RVec.size))
print(RRVec)
print("Количество элементов: {}".format(RRVec.size))

[0.22583395 0.3968098  0.17899647 0.72492209 0.94939115]
Количество элементов: 5
[0.94939115 0.72492209 0.17899647 0.3968098  0.22583395]
Количество элементов: 5


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [92]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [93]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [94]:
DMat=np.diag([1,2,3,4])
DMat[DMat==0]=7
print(DMat)


[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [95]:
np.tile(np.arange(5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [96]:
RMat=np.random.rand(10,10)
print('Исходная матрица: \n', RMat)
MMat=RMat-np.mean(RMat, axis=1)
print('\nМатрица после вычитания: \n', MMat)


Исходная матрица: 
 [[0.52060054 0.11198487 0.46732589 0.35092236 0.06975725 0.41246394
  0.61918568 0.88450517 0.0089113  0.35997326]
 [0.15166412 0.55689898 0.75258762 0.34912188 0.04631462 0.63168503
  0.04254949 0.45218714 0.39853326 0.2240782 ]
 [0.57120163 0.18299538 0.26983537 0.31884328 0.50397478 0.81369467
  0.87135768 0.36152081 0.75868888 0.57357876]
 [0.1022876  0.19743582 0.88978572 0.38258814 0.08436336 0.35138861
  0.11001148 0.20362089 0.84817741 0.23382573]
 [0.01459828 0.99943785 0.33399358 0.98476906 0.26080184 0.01750282
  0.27432305 0.48885332 0.8094507  0.9727443 ]
 [0.22818817 0.07919178 0.36650199 0.49470615 0.77253536 0.07111529
  0.55224172 0.78738858 0.35850488 0.63343016]
 [0.93275946 0.55544142 0.08808668 0.14669269 0.57437959 0.44376183
  0.2770712  0.30943246 0.49293995 0.11333564]
 [0.14113782 0.75281045 0.50926935 0.53479529 0.01534811 0.43333264
  0.06003596 0.52665889 0.03281786 0.24117121]
 [0.5351897  0.80989077 0.84821702 0.78075904 0.37242894 0.4

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [97]:
NRMat=np.random.rand(10,10)
print('Исходная матрица: \n ', NRMat)
NMMat=RMat-np.median(RMat, axis=0)
print('\nМатрица после вычитания: \n', NMMat)

Исходная матрица: 
  [[0.89059637 0.97734612 0.14978417 0.6525333  0.22534134 0.15163824
  0.69603583 0.8426831  0.80285344 0.99713763]
 [0.00326814 0.11493246 0.58717526 0.79344991 0.69069728 0.34082187
  0.0980987  0.90167518 0.96163823 0.30635862]
 [0.20172863 0.38208932 0.45245122 0.88166902 0.02244602 0.9037679
  0.01186108 0.24495143 0.31305435 0.74451504]
 [0.45895618 0.37915867 0.68257885 0.17465109 0.58798105 0.60039586
  0.53391735 0.36647041 0.81486583 0.28308547]
 [0.5833627  0.23296057 0.36204539 0.31300555 0.31355999 0.18807417
  0.93291448 0.7711903  0.84412805 0.49237421]
 [0.61305257 0.47796477 0.46090762 0.84643646 0.97665613 0.7750061
  0.75347331 0.35341401 0.30264019 0.91164261]
 [0.116395   0.19959621 0.87180773 0.73581271 0.53612701 0.3221409
  0.15814241 0.26749392 0.65478131 0.81719234]
 [0.47719844 0.88114447 0.01952532 0.67836024 0.51835827 0.71511489
  0.09035647 0.53555058 0.98170814 0.38290064]
 [0.88817834 0.37649921 0.593031   0.52937505 0.61867754 0.711

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [98]:
FMat=np.random.rand(5,5)
Mmax=np.max(FMat, axis=1, keepdims=True)
Mmin=np.min(FMat, axis=1, keepdims=True)
NFMat=np.hstack((FMat, Mmax))
NNFMat=np.hstack((NFMat, Mmin))
print('Исходная матрица: \n ', FMat)
print('\nМатрица после добавления столбцов: \n', NNFMat)

Исходная матрица: 
  [[0.39902358 0.95246538 0.91714721 0.88566538 0.42756269]
 [0.48861842 0.1750627  0.37081215 0.04771923 0.72633421]
 [0.7784773  0.09429602 0.59061158 0.71541042 0.79577501]
 [0.06193347 0.69813904 0.27929234 0.91339026 0.95175117]
 [0.51884786 0.25421987 0.81279863 0.36795804 0.16974165]]

Матрица после добавления столбцов: 
 [[0.39902358 0.95246538 0.91714721 0.88566538 0.42756269 0.95246538
  0.39902358]
 [0.48861842 0.1750627  0.37081215 0.04771923 0.72633421 0.72633421
  0.04771923]
 [0.7784773  0.09429602 0.59061158 0.71541042 0.79577501 0.79577501
  0.09429602]
 [0.06193347 0.69813904 0.27929234 0.91339026 0.95175117 0.95175117
  0.06193347]
 [0.51884786 0.25421987 0.81279863 0.36795804 0.16974165 0.81279863
  0.16974165]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [99]:
IVec=np.arange(1,52)

EVec=IVec[IVec%2 ==0]
print('\nВектор четных чисел: \n', EVec)
print('\nКоличество элементов: {}'.format(EVec.size))

OVec=IVec[IVec%2 !=0]
OOVec=OVec[0:25]
print('\nВектор нечетных чисел (с измененной размерностью): \n', OOVec)
print('\nКоличество элементов: {}'.format(OOVec.size))

EMat=EVec.reshape(5,5)
print('\nМатрица четных чисел: \n', EMat)

OMat=OOVec.reshape(5,5)
print('\nМатрица нечетных чисел: \n', OMat)

PMat=np.dot(EMat,OMat)
print('\nПроизведение матриц: \n', PMat)

print('\nОбратная матрица матрицы произведения: ')
try:
  InvMat= np.linalg.inv(PMat)
  print('\nобратная матрица: \n', InvMat)
except:
  print('обратной матрицы не сущесвует')



Вектор четных чисел: 
 [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]

Количество элементов: 25

Вектор нечетных чисел (с измененной размерностью): 
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]

Количество элементов: 25

Матрица четных чисел: 
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]

Матрица нечетных чисел: 
 [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]

Произведение матриц: 
 [[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]]

Обратная матрица матрицы произведения: 
обратной матрицы не сущесвует


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [100]:
ZMat=np.zeros((8,8), int)
print('\nИсходная матрица: \n', ZMat)
ZMat[::2,::2]=1
print('\nПервое заполнение единицами: \n', ZMat)
ZMat[1::2,1::2]=1
print('\nВторое заполнение единицами: \n', ZMat)


Исходная матрица: 
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Первое заполнение единицами: 
 [[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]

Второе заполнение единицами: 
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
